/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twisterdraw.view;

import java.awt.Color;
import javax.swing.JLabel;
import twisterdraw.controller.Controller;

/**
 *
 * @author Szymon
 */
public class TwisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form TwisterFrame
     */
    Controller controller;
    JLabel label = new JLabel("aaaaaaaaa");
    
    public TwisterFrame() {
        initComponents();
        startButton.setEnabled(false);
        controller = new Controller(resultPanel);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        sec30Button = new javax.swing.JButton();
        sec15Button = new javax.swing.JButton();
        sec10Button = new javax.swing.JButton();
        sec20Button = new javax.swing.JButton();
        resultPanel = new GamePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        sec30Button.setText("30 sec");
        sec30Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec30ButtonActionPerformed(evt);
            }
        });

        sec15Button.setText("15 sec");
        sec15Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec15ButtonActionPerformed(evt);
            }
        });

        sec10Button.setText("10 sec");
        sec10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec10ButtonActionPerformed(evt);
            }
        });

        sec20Button.setText("20 sec");
        sec20Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sec20ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 379, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sec10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec15Button, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sec30Button, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec20Button, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec20Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec30Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sec15Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        controller.startTheGame();
    }//GEN-LAST:event_startButtonActionPerformed

    private void sec10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec10ButtonActionPerformed
        controller.setTimeOfDraw(10000);
        startButton.setEnabled(true);
    }//GEN-LAST:event_sec10ButtonActionPerformed

    private void sec15ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec15ButtonActionPerformed
        controller.setTimeOfDraw(15000);
        startButton.setEnabled(true);
    }//GEN-LAST:event_sec15ButtonActionPerformed

    private void sec20ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec20ButtonActionPerformed
        controller.setTimeOfDraw(20000);
        startButton.setEnabled(true);        
    }//GEN-LAST:event_sec20ButtonActionPerformed

    private void sec30ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sec30ButtonActionPerformed
        controller.setTimeOfDraw(30000);
        startButton.setEnabled(true);        
    }//GEN-LAST:event_sec30ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton sec10Button;
    private javax.swing.JButton sec15Button;
    private javax.swing.JButton sec20Button;
    private javax.swing.JButton sec30Button;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
